---
title: "smic_core_microbiome"
output: html_document
date: "2026-03-13"
---



```{r }

decontam_filter_nonegs <- readRDS("C:/Users/Carolyn/Documents/seastar-microbiome-paper/code/decontam_filter_nonegs.rds")

```



```{r}
library(microbiome); packageVersion("microbiome")
library(RColorBrewer)
library(reshape)
library(dplyr)
library(tidyr)

```


Subset by sea star species
```{r}

healthy_derm  <- ps_filter(
  decontam_filter_nonegs,
  (Host == "Dermasterias imbricata" & DermisType2 == "H_healthy"))


healthy_pisaster  <- ps_filter(
  decontam_filter_nonegs,
  (Host == "Pisaster ochraceus" & DermisType2 == "H_healthy"))

seawater  <- ps_filter(
  decontam_filter_nonegs,
  (Host == "Seawater"))

```



##### CORE MICROBIOME ANALYSIS FOR EACH HOST/ENVIRONMENT #####

```{r core microbiome PISASTER HEALTHY}

#first need to transform the data
healthy_pisaster_trans <- microbiome::transform(healthy_pisaster, "compositional")

# Agglomerate first -- since we have repeated Genera in the taxa table
pisaster_healthy_genus <- tax_glom(healthy_pisaster_trans, "Genus")

# Melt phyloseq object to data frame
df_core_pisaster <- psmelt(pisaster_healthy_genus)

# Detect core genera 
core_genus_pisaster_healthy <- core_members(pisaster_healthy_genus, detection = 0.001, prevalence = 75/100)

#map back to taxonomic names rather than ASV Ids
core_taxa_pioc <- tax_table(pisaster_healthy_genus)[core_genus_pisaster_healthy, ]

core_tax_df_pioc <- as.data.frame(core_taxa_pioc)

pioc_taxa_list<-core_tax_df_pioc$Genus

pioc_taxa_list


#### Option 1: Add a Core column to the melted data frame ####
# Add a new column to df_core_pisaster data frame to indicate the core genera or other
df_core_pisaster <- df_core_pisaster %>% mutate(Core = ifelse(OTU %in% core_genus_pisaster_healthy, Genus, "Other")) 

df_core_pisaster

#set plotting order
unique(df_core_pisaster$Core)
df_core_pisaster$Core = factor(df_core_pisaster$Core, levels = c("Spirochaetia Class","Spirochaetaceae Family", "Salinispira", "Rhodobacteraceae Family", "Yoonia-Loktanella", "Flavobacteriaceae Family", "Polaribacter", "Saprospiraceae Family", "Endozoicomonas","Reichenbachiella","Roseibacillus","Rubritalea","Other" ))                        

 write.csv(df_core_pisaster, "df_core_pisaster.csv")

# Plot everything

#df_core_pisaster$Date <- as.Date(df_core_pisaster$Date, format="%Y-%m-%d")
df_core_pisaster$YearMonth<-factor(df_core_pisaster$YearMonth)

core_colors <- c(
  "Spirochaetia Class" = "#8B004B",
  "Spirochaetaceae Family" = "#B2182B",
  "Salinispira" = "#EF6548",
  "Rhodobacteraceae Family" = "#F4A261",
  "Yoonia-Loktanella" = "#E9C46A",
  "Flavobacteriaceae Family" = "#F1E4A6",
  "Polaribacter" = "#D9E4A5",
  "Saprospiraceae Family" = "#B8DE8F",
  "Endozoicomonas" = "#7FCDBB",
  "Reichenbachiella" = "#41B6C4",
  "Roseibacillus" = "#1D91C0",
  "Rubritalea" = "#6A51A3",
  "Other" = "grey80",
  "NA" = "grey40"
)

df_core_pisaster$Core
pis_core_plot<-df_core_pisaster %>%
ggplot(aes(SiteType, Abundance, fill = Core)) +
  geom_bar(stat = "identity", position = "fill") +
  theme_classic() +
  scale_fill_manual(values = core_colors, drop = FALSE) +
  #facet_wrap(~SiteType) +
  #theme(axis.text.x = element_text(angle = 30, hjust = 1)) + 
  ggtitle("P. ochraceous") + theme(plot.title = element_text(size = 10, face = "italic"))

pis_core_plot
```

#now derm
```{r}

#first need to transform the data
healthy_derm_trans <- microbiome::transform(healthy_derm, "compositional")

# Agglomerate first -- since we have repeated Genera in the taxa table
derm_healthy_genus <- tax_glom(healthy_derm_trans, "Genus")

# Melt phyloseq object to data frame
df_core_derm <- psmelt(derm_healthy_genus)

# Detect core genera 
core_genus_derm <- core_members(derm_healthy_genus, detection = 0.001, prevalence = 75/100)

#map back to taxonomic names rather than ASV Ids
core_taxa_derm <- tax_table(derm_healthy_genus)[core_genus_derm, ]

core_tax_df <- as.data.frame(core_taxa_derm)

derm_taxa_list<-core_tax_df$Genus

derm_taxa_list

#### Option 1: Add a Core column to the melted data frame ####
# Add a new column to df_core_pisaster data frame to indicate the core genera or other
df_core_derm <- df_core_derm %>% mutate(Core = ifelse(OTU %in% core_genus_derm, Genus, "Other")) 


#set plotting order
unique(df_core_derm$Core)

df_core_derm$Core = factor(df_core_derm$Core, levels = c("Saprospiraceae Family","Rubritalea", "Flavobacteriaceae Family", "Rhodobacteraceae Family","Other" ))                        

# write.csv(df_core_pisaster, "df_core_pisaster.csv")

# Plot everything

df_core_derm$YearMonth<-factor(df_core_derm$YearMonth)

derm_core_plot<-df_core_derm %>%
ggplot(aes(SiteType, Abundance, fill = Core)) +
  geom_bar(stat = "identity", position = "fill") +
  theme_classic()+
  scale_fill_manual(values = core_colors, drop = FALSE) +
 # facet_wrap(~SiteType) +
 # theme(axis.text.x = element_text(angle = 30, hjust = 1)) + 
  ggtitle("D. imbricata") + theme(plot.title = element_text(size = 10, face = "italic"))

derm_core_plot


#to make sure colors of core taxa are consistent when two species are combined
core_levels <- c(
  "Spirochaetia Class",
  "Spirochaetaceae Family",
  "Salinispira",
  "Rhodobacteraceae Family",
  "Yoonia-Loktanella",
  "Flavobacteriaceae Family",
  "Polaribacter",
  "Saprospiraceae Family",
  "Endozoicomonas",
  "Reichenbachiella",
  "Roseibacillus",
  "Rubritalea",
  "Other",
  "NA"
)


df_core_derm$Core <- factor(df_core_derm$Core, levels = core_levels)
df_core_pisaster$Core <- factor(df_core_pisaster$Core, levels = core_levels)


ggarrange(pis_core_plot, derm_core_plot, ncol=1, common.legend=TRUE, align = "v", legend = "right", labels = c("a", "b"))


```

And seawater

```{r}
#first need to transform the data
seawater_trans <- microbiome::transform(seawater, "compositional")

# Agglomerate first -- since we have repeated Genera in the taxa table
seawater_genus <- tax_glom(seawater_trans, "Genus")

# Melt phyloseq object to data frame
df_core_seawater <- psmelt(seawater_genus)

# Detect core genera 
core_genus_seawater <- core_members(seawater_genus, detection = 0.001, prevalence = 75/100)

#map back to taxonomic names rather than ASV Ids
core_taxa_seawater <- tax_table(seawater_genus)[core_genus_seawater, ]

core_tax_df_seawater <- as.data.frame(core_taxa_seawater)


seawater_taxa_list<-core_tax_df_seawater$Genus

seawater_taxa_list

#### Option 1: Add a Core column to the melted data frame ####
# Add a new column to df_core_pisaster data frame to indicate the core genera or other
df_core_seawater <- df_core_seawater %>% mutate(Core = ifelse(OTU %in% core_genus_seawater, Genus, "Other")) 


#set plotting order
unique(df_core_seawater$Core)
```



If we wanted to do a venn diagram to compare the core taxa between sea stars

```{r}


library(ggVennDiagram)

venn <- list(
  Derm = derm_taxa_list,
  Pioc = pioc_taxa_list, 
  Seawater = seawater_taxa_list)

ggVennDiagram(venn, label = "count") +
  scale_fill_gradient(low = "white", high = "steelblue")


Derm <- unique(derm_taxa_list)
Pioc <- unique(pioc_taxa_list)
Seawater <- unique(seawater_taxa_list)

derm_only <- setdiff(Derm, union(Pioc, Seawater))
pioc_only <- setdiff(Pioc, union(Derm, Seawater))
seawater_only <- setdiff(Seawater, union(Derm, Pioc))

derm_pioc <- setdiff(intersect(Derm, Pioc), Seawater)
derm_seawater <- setdiff(intersect(Derm, Seawater), Pioc)
pioc_seawater <- setdiff(intersect(Pioc, Seawater), Derm)

all_three <- Reduce(intersect, list(Derm, Pioc, Seawater))

all_three


#Could also incoporate the indicator taxa here



venn2 <- list(
  Derm = derm_indicators,
  Pioc = pioc_indicators, 
  Seawater = seawater_indicators=)

ggVennDiagram(venn2, label = "count") +
  scale_fill_gradient(low = "white", high = "mediumorchid1")


derm_indicators <- list("Bdellovibrio", "EC94", "Peredibacter", "Rhodobacteraceae Family", "Thiothrix")

pioc_indicators <- list("Candidatus_Hepatoplasma", "Endozoicomonas", "Gracilibacteria", "Psychroflexus", "Reichenbachiella", "Salinispira", "Spirochaetaceae Family", "Spirochaetia Class")

library(datapasta)
seawater_indicators <- list("AEGEAN-169_marine_group", "Amylibacter", "Ascidiaceihabitans", "BD1-7_clade", "Candidatus_Actinomarina", "Candidatus_Aquiluna", "Candidatus_Nitrosopumilus", "Candidatus_Puniceispirillum", "CL500-3", "Clade_Ia", "Clade_II", "Clade_III", "Clade_IV", "Cryomorphaceae Family", "Defluviicoccales Order", "Ectothiorhodospiraceae Family", "Flavicella", "Fluviicola", "Formosa", "Ga0077536", "HOC36", "IS-44", "KI89A_clade", "Kordiimonadales Order", "Lentimonas", "Luminiphilus", "Magnetospira", "Magnetospiraceae Family", "Marine_Group_II", "Marinifilaceae Family", "Marinimicrobia_(SAR406_clade)", "Marinoscillum", "MB11C04_marine_group", "Nitrincolaceae Family", "Nitrosomonas", "Nitrosopumilaceae Family", "NS10_marine_group", "NS11-12_marine_group", "NS2b_marine_group", "NS3a_marine_group", "NS4_marine_group", "NS5_marine_group", "NS7_marine_group", "NS9_marine_group", "OCS116_clade", "OM182_clade", "OM43_clade", "OM60(NOR5)_clade", "OM75_clade", "Pelagicoccus", "Pirellulaceae Family", "Planktomarina", "Porticoccus", "PS1_clade", "Pseudohongiella", "Puniceispirillales Order", "RS62_marine_group", "SAR116_clade", "SAR324_clade(Marine_group_B)", "SAR86_clade", "SAR92_clade", "SCGC_AAA164-E04", "Spongiibacteraceae Family", "Stappiaceae", "SUP05_cluster", "Synechococcus_CC9902", "Thiotrichaceae Family")

seawater_indicators

derm_core <-list("EC94", "Flavobacteriaceae Family", "Saprospiraceae Family", "Rhodobacteraceae Family", "Rubritalea")

pioc_core <- list("Endozoicomonas", "Flavobacteriaceae Family", "Polaribacter", "Reichenbachiella", "Rhodobacteraceae Family", "Salinispira", "Spirochaetaceae Family", "Spirochaetia Class", "Roseibacillus", "Rubritalea", "Saprospiraceae Family","Yoonia-Loktanella")





pisaster_indicator <- as.character(unlist(pioc_indicators))
pisaster_core      <- as.character(unlist(pioc_core))
dermasterias_indicator <- as.character(unlist(derm_indicators))
dermasterias_core      <- as.character(unlist(derm_core))

pisaster_indicator <- unique(na.omit(pisaster_indicator))
pisaster_core      <- unique(na.omit(pisaster_core))
dermasterias_indicator <- unique(na.omit(dermasterias_indicator))
dermasterias_core      <- unique(na.omit(dermasterias_core))


venn_core_ind <- list(
  Derm_core = derm_taxa_list,
  Pioc_core = pioc_taxa_list,
  Derm_ind = derm_indicators,
  Pioc_ind = pioc_indicators
)


str(pisaster_indicator)
str(pisaster_core)
str(dermasterias_indicator)
str(dermasterias_core)

library(VennDiagram)

install.packages("VennDiagram")
library(VennDiagram)
library(grid)

venn.plot <- venn.diagram(
  x = list(
    Pisaster_Indicator = pisaster_indicator,
    Pisaster_Core = pisaster_core,
    Dermasterias_Indicator = dermasterias_indicator,
    Dermasterias_Core = dermasterias_core
  ),
  filename = NULL,
  fill = c("red", "blue", "green", "purple"),
  alpha = 0.5,
  cex = 1.5,
  cat.cex = 1.2
)

grid.draw(venn.plot)


library(UpSetR)

# Combine all taxa
all_taxa <- unique(c(pisaster_indicator,
                     pisaster_core,
                     dermasterias_indicator,
                     dermasterias_core))

# Create a presence/absence numeric data frame (0/1 instead of TRUE/FALSE)
df_upset <- data.frame(
  pisaster_indicator = as.integer(all_taxa %in% pisaster_indicator),
  pisaster_core = as.integer(all_taxa %in% pisaster_core),
  dermasterias_indicator = as.integer(all_taxa %in% dermasterias_indicator),
  dermasterias_core = as.integer(all_taxa %in% dermasterias_core)
)

# Add taxa names as rownames (optional, for tracing)
rownames(df_upset) <- all_taxa

df_upset

upset(df_upset, 
      sets = c("pisaster_indicator", "pisaster_core", 
               "dermasterias_indicator", "dermasterias_core"),
      order.by = "freq")

library(eulerr)

taxa_lists <- list(
  pisaster_indicator = pisaster_indicator,
  pisaster_core = pisaster_core,
  dermasterias_indicator = dermasterias_indicator,
  dermasterias_core = dermasterias_core
)

fit <- euler(taxa_lists)

library(scales)
colors <- grey(rescale(overlap_sizes, to = c(0.8, 0.3)))  # bigger overlaps = darker


plot(fit,
     fills = list(
       fill = colors,   # color by overlap size
       alpha = 0.6      # slightly transparent
     ),
     edges = TRUE,       # show circle edges
     quantities = TRUE,  # show counts
     labels = list(font = 2, cex = 1), # bold labels
     main = "Euler Diagram of 4 Taxa Lists with Overlap Coloring"
)

dev.off()

```



