---
title: "smic_alpha_diversity"
output: html_document
date: "2026-03-12"
---

First read in the phyloseq object that we need

```{r }

#read in the required QC'ed phyloseq object
decontam_filter_nonegs <- readRDS("C:/Users/Carolyn/Documents/seastar-microbiome-paper/code/decontam_filter_nonegs.rds")

```


```{r load required libraries}

library(phyloseq)
library(ggplot2)
library(microViz)
library(dplyr)
library(data.table)
library(tidyr)
library(RColorBrewer)

```

############### HOST ALPHA DIVERSITY ##################

```{r alpha diversity by host}

#we only want to look at healthy Pisaster along with Derm and seawater for these initial plots -- disease categories examined further down

#we will use inverse simpson index as it's the most robust to non-rarefied data

healthy_all <- ps_filter(
  decontam_filter_nonegs,
  (Host == "Pisaster ochraceus" & DermisType2 == "H_healthy") |
  (Host == "Dermasterias imbricata" & DermisType2 == "H_healthy") |
  (Host == "Seawater"))

richness_host <- data.frame(
  "InvSimpson" = phyloseq::estimate_richness(healthy_all, measures = "InvSimpson"),
  "Host" = phyloseq::sample_data(healthy_all)$Host, 
  "Region" = phyloseq::sample_data(healthy_all)$SiteType, 
  "Site" = phyloseq::sample_data(healthy_all)$Site, 
  "Year" = phyloseq::sample_data(healthy_all)$Year)

richness_host$Host<-factor(richness_host$Host)
richness_host$Region<-factor(richness_host$Region)
richness_host$Site<-factor(richness_host$Site)
richness_host$Year<-factor(richness_host$Year)

#Customize facet labels
#host_labels <- c(
 # "Dermasterias imbricata" = "italic('D. imbricata')",
#  "Pisaster ochraceus"     = "italic('P. ochraceus')",
 # "Seawater"               = "'Seawater'")


#boxplot
alpha_host_boxplot<-richness_host %>%
  pivot_longer(cols = "InvSimpson",
               names_to = "metric",
               values_to = "value") %>%
  ggplot(aes(x = Host, y = value, color = Host, fill = Host)) +
  geom_boxplot(alpha = 0.4, outlier.shape = NA, outlier.colour = NA) +
 geom_jitter(alpha=0.5, height = 0, width = .3) +
 #geom_jitter(aes(shape = Region), height = 0, width = .4) +
  labs(x = NULL, y = "Inv. Simpson", color = "Sample Type") +
  #facet_wrap(~Region, scales = "free") +
  scale_color_manual(values = c("#AD002AFF", "#925E9FFF","#0099B4FF"), name = "Sample Type", 
                     labels = c(expression(italic("D. imbricata")), expression(italic("P. ochraceus")),"Seawater")) +
  scale_fill_manual(values = c("#AD002AFF", "#925E9FFF","#0099B4FF"), name = "Sample Type", labels = c(expression(italic("D. imbricata")), expression(italic("P. ochraceus")),"Seawater")) +
  #scale_shape_manual(values = c(8, 15)) +
  theme_classic() +
  facet_wrap(~Region) +
  theme(legend.position="right") + guides(fill = "none", shape = "none", color ="none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_text(size = 13), axis.text.x = element_blank())
#remove x-axis labels because combining with beta div plot which has legend
  
 alpha_host_boxplot     #boxplot version
 
 saveRDS(alpha_host_boxplot, file = "alpha_host_boxplot.rds")

```

#Mixed effects models to test relative effects of host and region on alpha diversity (inv simpson index)

```{r}

packageVersion("phyloseq")
library(lme4)
library(MuMIn)
library(DHARMa)
library(performance)

#run 4 models to compare: 
#in this case we don't have a random effect. initially had year as a random effect but it was not adding any explanitory power to the model so removed

mod1_host<-glmer(InvSimpson~Host + (1 | Region/Site), data = richness_host, na.action = "na.fail", family=Gamma(link = "log"))

mod2_region<-glmer(InvSimpson~Region + (1 | Region/Site), data = richness_host, na.action = "na.fail", family=Gamma(link = "log"))

mod3_regionhost <- glmer(InvSimpson~Host*Region + (1 | Region/Site), data = richness_host, na.action = "na.fail", family=Gamma(link = "log"))

mod4_null<- glmer(InvSimpson~ 1 + (1 | Region/Site), data = richness_host, na.action = "na.fail", family=Gamma(link = "log"))


#comparing all 4 models
hostregion_sel<-model.sel(mod1_host, mod2_region, mod3_regionhost, mod4_null, rank = "AICc", beta = "sd")

hostregion_sel

#calculate R2 (marginal and conditional for each model)
r.squaredGLMM(mod1_host)
r.squaredGLMM(mod2_region)
r.squaredGLMM(mod3_regionhost)
r.squaredGLMM(mod4_null)


library(flextable)

hostregion_sel_df <- as.data.frame(hostregion_sel) %>%
  rownames_to_column(var = "hostregion_sel") %>%  # optional: make model names a column
  select(hostregion_sel, df, logLik, AICc, delta, weight)  # pick columns you want

# Make a Word-ready table
hostregion_table <- flextable(hostregion_sel_df) %>%
  autofit() %>%
  theme_vanilla()  # simple clean style

# Export to Word
library(officer)
doc_hostregion <- read_docx()
doc_hostregion <- body_add_flextable(doc_hostregion, hostregion_table)
print(doc_hostregion, target = "hostregion_table.docx")

```

########### SEASONAL ALPHA DIVERSITY   ######################

```{r alpha diversity by SEASON, seawater}

seawater  <- ps_filter(
  decontam_filter_nonegs,
  (Host == "Seawater"))

seawater
ntaxa(seawater)
nsamples(seawater)
sample_data(seawater)

### SEAWATER RICHNESS ###
richness_seawater <- data.frame(
  "InvSimpson" = phyloseq::estimate_richness(seawater, measures = "InvSimpson"),
  "Season" = phyloseq::sample_data(seawater)$Season, 
  "Region" = phyloseq::sample_data(seawater)$SiteType,
  "Year" = phyloseq::sample_data(seawater)$Year, 
  "DayOfYear" = phyloseq::sample_data(seawater)$DayOfYear, 
  "Month" = phyloseq::sample_data(seawater)$Month, 
  "Site" = phyloseq::sample_data(seawater)$Site)

richness_seawater$Year<-factor(richness_seawater$Year)
richness_seawater$Season <- factor(
  richness_seawater$Season,
  levels = c("Winter", "Spring", "Summer", "Fall"))



#Inverse simpson seawater by region and year

seawater_seasonal<-richness_seawater %>%
    pivot_longer(cols = "InvSimpson",
               names_to = "metric",
               values_to = "value") %>%
  ggplot(aes(x = Season, y = value, color = Season, fill = Season)) +
  geom_boxplot(alpha = 0.4, outlier.shape = NA) +
 geom_jitter(aes(shape = Region), alpha=0.3, height = 0, width = .2) +
  labs(x = NULL, y = "Inv. Simpson") +
  scale_color_manual(values = c("#05668D", "#00A896", "#9DD9D2", "#FE5E41")) +
  scale_fill_manual(values = c("#05668D", "#00A896", "#9DD9D2", "#FE5E41")) +
  scale_shape_manual(values = c(8, 15)) +
  theme_classic() + 
  #theme(axis.text.x = element_blank()) +
  facet_wrap(~Year, ncol=4) +
  scale_y_continuous(limits = c(0, 200)) +
  guides(color = "none", fill = "none") +
  ggtitle("Seawater") + theme(plot.title = element_text(size = 10)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
   theme(strip.background = element_blank() # This removes the box and background
  )


seawater_seasonal

```


```{r mixed effect model richness seawater}

richness_seawater

mod1_season<-glmer(InvSimpson~Season + (1 |Region), data = richness_seawater, na.action = "na.fail", family=Gamma(link = "log"))

mod2_year<-glmer(InvSimpson~Year + (1 |Region), data = richness_seawater, na.action = "na.fail", family=Gamma(link = "log"))

mod3_seasonyear <- glmer(InvSimpson~Season*Year +  (1 |Region), data = richness_seawater, na.action = "na.fail", family=Gamma(link = "log"))

mod4_nullseason<- glmer(InvSimpson~ 1+ (1 |Region), data = richness_seawater, na.action = "na.fail", family=Gamma(link = "log"))


#comparing all 4 models
season_sel<-model.sel(mod1_season, mod2_year, mod3_seasonyear, mod4_nullseason, rank = "AICc", beta = "sd")

season_sel

season_sel_df <- as.data.frame(season_sel) %>%
  rownames_to_column(var = "season_sel") %>%  # optional: make model names a column
  select(season_sel, df, logLik, AICc, delta, weight)  # pick columns you want

# Make a Word-ready table
ft_season_sw <- flextable(season_sel_df) %>%
  autofit() %>%
  theme_vanilla()  # simple clean style

# Export to Word
library(officer)
doc_season_sw <- read_docx()
doc_season_sw<- body_add_flextable(doc_season_sw, ft_season_sw)
print(doc_season_sw, target = "season_seawater_table.docx")


#calculate R2 (marginal and conditional for each model)
r.squaredGLMM(mod1_season)
r.squaredGLMM(mod2_year)
r.squaredGLMM(mod3_seasonyear)
r.squaredGLMM(mod4_nullseason)


# Simulate residuals
simulated_residuals_seawater <- simulateResiduals(mod1_season)

# Plot the diagnostics
plot(simulated_residuals_seawater)
plotResiduals(simulated_residuals_seawater)

```


```{r alpha diversity by SEASON, Derm}

healthy_derm  <- ps_filter(
  decontam_filter_nonegs,
  (Host == "Dermasterias imbricata" & DermisType2 == "H_healthy"))

### DERM ###
richness_derm <- data.frame(
  "InvSimpson" = phyloseq::estimate_richness(healthy_derm, measures = "InvSimpson"),
  "Season" = phyloseq::sample_data(healthy_derm)$Season, 
  "Region" = phyloseq::sample_data(healthy_derm)$SiteType,
  "Year" = phyloseq::sample_data(healthy_derm)$Year, 
  "DayOfYear" = phyloseq::sample_data(healthy_derm)$DayOfYear, 
  "Month" = phyloseq::sample_data(healthy_derm)$Month, 
  "Site" = phyloseq::sample_data(healthy_derm)$Site)

richness_derm$Site<-factor(richness_derm$Site)
richness_derm$Season <- factor(
  richness_derm$Season,
  levels = c("Winter", "Spring", "Summer", "Fall"))

#Inverse simpson seawater by region and year
derm_seasonal<- richness_derm %>%
    pivot_longer(cols = "InvSimpson",
               names_to = "metric",
               values_to = "value") %>%
  ggplot(aes(x = Season, y = value, color = Season, fill = Season)) +
  geom_boxplot(alpha=0.4, outlier.shape = NA) +
 geom_jitter(aes(shape = Region), height = 0, width = .2, alpha = 0.3) +
  labs(x = NULL, y = "Inv. Simpson") +
    scale_color_manual(values = c("#05668D", "#00A896", "#9DD9D2", "#FE5E41")) +
  scale_fill_manual(values = c("#05668D", "#00A896", "#9DD9D2", "#FE5E41")) +
  scale_shape_manual(values = c(8, 15)) +
  theme_classic() +
  facet_wrap(~Year, ncol=4) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) + 
  guides(color = "none", fill = "none") +
  ggtitle("D. imbricata") + theme(plot.title = element_text(size = 10, face = "italic")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
   theme(strip.background = element_blank() # This removes the box and background
  )
  
derm_seasonal

```


```{r mixed effects model derm season}
richness_derm

mod1_season_derm<-glmer(InvSimpson~Season + (1 |Region), data = richness_derm, na.action = "na.fail", family=Gamma(link = "log"))

mod2_year_derm<-glmer(InvSimpson~Year + (1 |Region), data = richness_derm, na.action = "na.fail", family=Gamma(link = "log"))

mod3_seasonyear_derm<- glmer(InvSimpson~Season*Year + (1 | Region ), data = richness_derm, na.action = "na.fail", family=Gamma(link = "log"))

mod4_nullseason_derm<- glmer(InvSimpson~ 1 + (1 | Region ), data = richness_derm, na.action = "na.fail", family=Gamma(link = "log"))


#boundary (singular) fit: see help('isSingular') warning for all

#comparing all 4 models
derm_sel<-model.sel(mod1_season_derm, mod2_year_derm, mod3_seasonyear_derm, mod4_nullseason_derm, rank = "AICc", beta = "sd")

derm_sel

derm_sel_df <- as.data.frame(derm_sel) %>%
  rownames_to_column(var = "derm_sel") %>%  # optional: make model names a column
  select(derm_sel, df, logLik, AICc, delta, weight)  # pick columns you want

# Make a Word-ready table
ft_season_derm <- flextable(derm_sel_df) %>%
  autofit() %>%
  theme_vanilla()  # simple clean style

# Export to Word
doc_season_derm <- read_docx()
doc_season_derm<- body_add_flextable(doc_season_derm, ft_season_derm)
print(doc_season_derm, target = "season_derm_table.docx")


#calculate R2 (marginal and conditional for each model)
r.squaredGLMM(mod1_season_derm)
r.squaredGLMM(mod2_year_derm)
r.squaredGLMM(mod3_seasonyear_derm)
r.squaredGLMM(mod4_nullseason_derm)

```


```{r alpha diversity by SEASON, Pisaster}

healthy_pisaster  <- ps_filter(
  decontam_filter_nonegs,
  (Host == "Pisaster ochraceus" & Disease_Status_Star == "healthy"))

### PISASTER ###
richness_pis <- data.frame(
  "InvSimpson" = phyloseq::estimate_richness(healthy_pisaster, measures = "InvSimpson"),
  "Season" = phyloseq::sample_data(healthy_pisaster)$Season, 
  "Region" = phyloseq::sample_data(healthy_pisaster)$SiteType,
  "Year" = phyloseq::sample_data(healthy_pisaster)$Year, 
  "DayOfYear" = phyloseq::sample_data(healthy_pisaster)$DayOfYear, 
  "Month" = phyloseq::sample_data(healthy_pisaster)$Month)


richness_pis$Season <- factor(
  richness_pis$Season,
  levels = c("Winter", "Spring", "Summer", "Fall"))


pis_seasonal<- richness_pis %>%
    pivot_longer(cols = "InvSimpson",
               names_to = "metric",
               values_to = "value") %>%
  ggplot(aes(x = Season, y = value, color = Season, fill = Season)) +
  geom_boxplot(alpha=0.4, outlier.shape = NA) +
 geom_jitter(aes(shape = Region), height = 0, width = .2, alpha = 0.3) +
  labs(x = NULL, y = "Inv. Simpson") +
    scale_color_manual(values = c("#05668D", "#00A896", "#9DD9D2", "#FE5E41")) +
  scale_fill_manual(values = c("#05668D", "#00A896", "#9DD9D2", "#FE5E41")) +
  scale_shape_manual(values = c(8, 15)) +
  theme_classic() +
  facet_wrap(~Year, ncol=4) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) + 
  guides(color = "none", fill = "none") +
  ggtitle("P. ochraceus") + theme(plot.title = element_text(size = 10, face = "italic")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(strip.background = element_blank() # This removes the box and background
  )
 

pis_seasonal  
derm_seasonal
seawater_seasonal

#combining all 3 hosts for alpha diversity
  library(ggpubr)

season_panel<-ggarrange(seawater_seasonal, derm_seasonal, pis_seasonal, common.legend=TRUE, ncol=1, align = "v", legend = "right", labels = c("A", "B", "C"))

season_panel

ggsave(plot = season_panel, "season_panel.jpeg", dpi=300, width=9, height=8, units="in")
```


```{r mixed effects model pis season}

richness_pis

mod1_season_pis<-glmer(InvSimpson~Season + (1 | Region), data = richness_pis, na.action = "na.fail", family=Gamma(link = "log"))

mod2_year_pis<-glmer(InvSimpson~Year + (1 | Region), data = richness_pis, na.action = "na.fail", family=Gamma(link = "log"))

mod3_seasonyear_pis<- glmer(InvSimpson~Season*Year + (1 | Region ), data = richness_pis, na.action = "na.fail", family=Gamma(link = "log"))

mod4_nullseason_pis<- glmer(InvSimpson~ 1 + (1 | Region), data = richness_pis, na.action = "na.fail", family=Gamma(link = "log"))


#comparing all 4 models
pis_sel<-model.sel(mod1_season_pis, mod2_year_pis, mod3_seasonyear_pis, mod4_nullseason_pis, rank = "AICc", beta = "sd")

pis_sel

pis_sel_df <- as.data.frame(pis_sel) %>%
  rownames_to_column(var = "pis_sel") %>%  # optional: make model names a column
  select(pis_sel, df, logLik, AICc, delta, weight)  # pick columns you want

# Make a Word-ready table
ft_season_pis <- flextable(pis_sel_df) %>%
  autofit() %>%
  theme_vanilla()  # simple clean style

# Export to Word
doc_season_pis <- read_docx()
doc_season_pis <- body_add_flextable(doc_season_pis, ft_season_pis)
print(doc_season_pis, target = "season_pis_table.docx")


#calculate R2 (marginal and conditional for each model)
r.squaredGLMM(mod1_season_pis)
r.squaredGLMM(mod2_year_pis)
r.squaredGLMM(mod3_seasonyear_pis)
r.squaredGLMM(mod4_nullseason_pis)

```


##### WASTING LEVELS ALPHA DIVERSITY ######

```{r alpha diversity by wasting score, Pisaster}

pisaster_all <- ps_filter(
  decontam_filter_nonegs,
  (Host == "Pisaster ochraceus"))


sample_data(pisaster_all)

richness_wasting <- data.frame(
  "InvSimpson" = phyloseq::estimate_richness(pisaster_all, measures = "InvSimpson"), 
  "Region" = phyloseq::sample_data(pisaster_all)$SiteType, 
  "WastingCategory" = phyloseq::sample_data(pisaster_all)$WastingCategory, 
  "WastingScore" = phyloseq::sample_data(pisaster_all)$WastingScore, 
   "DermisType" = phyloseq::sample_data(pisaster_all)$DermisType, 
  "Year" = phyloseq::sample_data(pisaster_all)$Year)


#Inverse simpson index by host
richness_wasting_plot<-richness_wasting %>%
  pivot_longer(cols = "InvSimpson",
               names_to = "metric",
               values_to = "value") %>%
  ggplot(aes(x = WastingCategory, y = value, color = WastingCategory)) +
 geom_boxplot(outlier.color = NA)  +
 geom_jitter(aes(shape = WastingScore), alpha=0.3, height = 0, width = .2) +
  labs(x = NULL, y = " Inv. Simpson") +
  facet_wrap(~Region) +
  scale_color_manual(values = c("lightseagreen", "mediumorchid1", "mediumorchid4"), name = "Host Type") +
  #scale_fill_manual(values = alpha(c("#AD002AFF", "#925E9FFF", "darkblue")), 0.5) +
  theme_classic() +
  theme(legend.position="right") +
  theme(axis.text.x = element_text(hjust = 1, size = 8)) + 
  guides(color = "none") +
  theme(strip.background = element_blank())
  #ggtitle("Pisaster ochraceous") + theme(plot.title = element_text(size = 10, face = "italic"))

richness_wasting_plot
  
```


```{r mixed effects model pisaster wasting score}
richness_wasting


mod1_wastingcat<-glmer(InvSimpson~WastingCategory + (1 | Region), data = richness_wasting, na.action = "na.fail", family=Gamma(link = "log"))

mod2_year_only<-glmer(InvSimpson~Year + (1 | Region), data = richness_wasting, na.action = "na.fail", family=Gamma(link = "log"))

mod3_wastingyear<- glmer(InvSimpson~WastingCategory*Year + (1 | Region), data = richness_wasting, na.action = "na.fail", family=Gamma(link = "log"))

mod4_null_wasting<- glmer(InvSimpson~ 1 + (1 | Region), data = richness_wasting, na.action = "na.fail", family=Gamma(link = "log"))


#comparing all 4 models
wasting_sel<-model.sel(mod1_wastingcat, mod2_year_only, mod3_wastingyear, mod4_null_wasting, rank = "AICc", beta = "sd")

wasting_sel

wasting_sel_df <- as.data.frame(wasting_sel) %>%
  rownames_to_column(var = "wasting_sel") %>%  # optional: make model names a column
  select(wasting_sel, df, logLik, AICc, delta, weight)  # pick columns you want

# Make a Word-ready table
ft_wasting_pis <- flextable(wasting_sel_df) %>%
  autofit() %>%
  theme_vanilla()  # simple clean style

# Export to Word
doc_wasting_pis <- read_docx()
doc_wasting_pis <- body_add_flextable(doc_wasting_pis, ft_wasting_pis)
print(doc_wasting_pis, target = "wasting_pis_table.docx")

#calculate R2 (marginal and conditional for each model)
r.squaredGLMM(mod1_wastingcat)
r.squaredGLMM(mod2_year_only)
r.squaredGLMM(mod3_wastingyear)
r.squaredGLMM(mod4_null_wasting)


packageVersion("indicspecies")


```


```{r alpha diversity by wasting within Pisaster}

pisaster_all <- ps_filter(
  decontam_filter_nonegs,
  (Host == "Pisaster ochraceus"))

sample_data(pisaster_all)

richness_wasting <- data.frame(
  "InvSimpson" = phyloseq::estimate_richness(pisaster_all, measures = "InvSimpson"), 
  "Region" = phyloseq::sample_data(pisaster_all)$SiteType, 
  "WastingCategory" = phyloseq::sample_data(pisaster_all)$WastingCategory, 
  "WastingScore" = phyloseq::sample_data(pisaster_all)$WastingScore,
  "TissueType" = phyloseq::sample_data(pisaster_all)$DermisType2,
  "Year" = phyloseq::sample_data(pisaster_all)$Year)



#Inverse simpson index by wasting cat
richness_wastingcat<-richness_wasting %>%
  pivot_longer(cols = "InvSimpson",
               names_to = "metric",
               values_to = "value") %>%
  ggplot(aes(x = WastingCategory, y = value, color = WastingCategory, fill = WastingCategory)) +
 geom_boxplot(alpha = 0.4, outlier.shape = NA, outlier.colour = NA)  +
 geom_jitter(aes(shape = WastingScore), alpha=0.4, height = 0, width = .3) +
  labs(x = NULL, y = " Inv. Simpson") +
  facet_wrap(~Region, scales = "free", axes = "all_x") +
  scale_color_manual(values = c("lightseagreen", "mediumorchid1", "mediumorchid4"), name = "Wasting Category") +
  scale_fill_manual(values = c("lightseagreen", "mediumorchid1", "mediumorchid4"), name = "Wasting Category") +
  theme_classic() +
  theme(legend.position="right") +
  guides(color = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_text(size = 12, face = "bold"))
  #ggtitle("Pisaster ochraceous") + theme(plot.title = element_text(size = 10, face = "italic"))

richness_wastingcat

richness_wasting<- richness_wasting %>%
  mutate(TissueType = factor(TissueType, levels = c("H_healthy", "H_diseased", "L_diseased")))


#Inverse simpson index by tissue type
richness_tissuetype<-richness_wasting %>%
  pivot_longer(cols = "InvSimpson",
               names_to = "metric",
               values_to = "value") %>%
  ggplot(aes(x = TissueType, y = value, color = TissueType, fill = TissueType)) +
 geom_boxplot(alpha = 0.4, outlier.shape = NA, outlier.colour = NA)  +
 geom_jitter(aes(shape = WastingScore), alpha=0.4, height = 0, width = .3) +
  labs(x = NULL, y = " Inv. Simpson") +
  facet_wrap(~Region, scales = "free", axes = "all_x") +
  scale_color_manual(values = c("olivedrab", "deepskyblue", "deepskyblue4"), name = "Tissue Type") + 
  scale_fill_manual(values = c("olivedrab", "deepskyblue", "deepskyblue4"), name = "Tissue Type") +
  theme_classic() +
  scale_x_discrete(labels = c("AsympH", "WastingNL", "WastingL")) +
  theme(legend.position="right") +
  guides(color = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_text(size = 0, face = "bold"))

richness_tissuetype

  #ggtitle("Pisaster ochraceous") + theme(plot.title = element_text(size = 10, face = "italic")) +


wasting_alpha<-ggarrange(richness_wastingcat, richness_tissuetype, common.legend=TRUE, ncol=1, align = "v", legend = "right", labels = c("A", "B"))

wasting_alpha

ggsave(plot = wasting_alpha, "wasting_alpha.jpeg", dpi=300, width=9, height=7, units="in")

  
```

