---
title: "smic_vibrio"
output: html_document
date: "2026-03-15"
---


```{r }

decontam_filter_nonegs <- readRDS("C:/Users/Carolyn/Documents/seastar-microbiome-paper/code/decontam_filter_nonegs.rds")

```


```{r}
library(microbiome); packageVersion("microbiome")
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(phyloseq)
library(microViz)
library(ggpubr)
library(reshape2)
```

to look at vibrio relative abundances across both sea star species 
```{r}

decontam_filter_nonegs

seastars_ps <-  decontam_filter_nonegs %>%
  ps_filter(Host %in% c("Pisaster ochraceus", "Dermasterias imbricata", "Seawater"))

seastars_ps_rel <- transform_sample_counts(seastars_ps, function(x) x / sum(x))

seastars_ps_glom <-speedyseq::tax_glom(seastars_ps_rel, taxrank = "Species")

ps_vibrio <- subset_taxa(seastars_ps_glom, Species == "Vibrio_pectenicida")

#Melt to long format
seastars_vibrio <- psmelt(ps_vibrio)

seastars_vibrio$Season <- factor(
  seastars_vibrio$Season,
  levels = c("Winter", "Spring", "Summer", "Fall"))

#make a plot with all the data, non-transformed 
stars_vibrio_plot<-ggplot(seastars_vibrio, aes(x = Host, 
               y = Abundance, 
               color = Host)) +
  #eom_boxplot() +
  geom_jitter(width = 0.2, alpha = 0.4) +
  theme_classic() +
  ylab("Vpec Relative Abundance") +
  #facet_wrap(~SiteType) +
  scale_color_manual(values = c("#AD002AFF", "#925E9FFF", "#0099B4FF")) + 
  theme(legend.position = "none") +
  scale_x_discrete(labels = c("D. imbricata", "P. ochraceus", "Seawater")) +
  theme(strip.background = element_blank()) +
  theme(axis.title.x = element_blank())+
  ggtitle("Host")  
#scale_y_sqrt()

stars_vibrio_plot

#trying a square root transformation on the x-axis and plotting through time

seastars_vibrio$Month <- factor(
  seastars_vibrio$Month,
  levels = c("1", "2", "5", "6", "7", "8", "9", "11", "12"))

seastars_vibrio$Host <- recode(seastars_vibrio$Host,
  "Dermasterias imbricata" = "italic(D.~imbricata)",
  "Pisaster ochraceus"     = "italic(P.~ochraceus)",
  "Seawater"               = "Seawater"
)

species_labels <- c(
  "Dermasterias imbricata" = "italic(D.~imbricata)",
  "Pisaster ochraceus"     = "italic(P.~ochraceus)",
  "Seawater"               = "Seawater"
)

stars_vibrio_plot2<-ggplot(seastars_vibrio, aes(x = Month, y = Abundance, color = Season)) +
  #geom_boxplot() +
  geom_jitter(aes(shape = SiteType), width = 0.3, alpha = 0.7) +
  theme_classic() +
 scale_color_manual(values = c("#05668D", "#00A896", "#9DD9D2", "#FE5E41")) +
  scale_shape_manual(values = c(8, 15), name = "Region")+
  ylab("sqrt(Rel. Abun.)") +
  facet_wrap(~Host,  labeller = label_parsed) +
  theme(strip.background = element_blank())  + scale_y_sqrt()
  #guides(color = "none")  


stars_vibrio_plot2



```


```{r}
#now only within pisaster, wasting levels
#remove zero values and try transforming the relative abundance

pisaster_vibrio <- seastars_vibrio %>%
  filter(Host %in% c("Pisaster ochraceus"))

pisaster_vibrio


#plot Vibrio across wasting categories
pis_vibrio_plot<-ggplot(pisaster_vibrio, aes(x = WastingCategory, 
               y = Abundance, 
               color = WastingCategory)) +
  #geom_boxplot() + 
  geom_jitter(width = 0.2, alpha = 0.7) +
  theme_classic() +
  ylab("Vpec Relative Abundance") +
  #facet_wrap(~SiteType) +
  scale_color_manual(values = c("lightseagreen", "mediumorchid1", "mediumorchid4"),
    name = "Wasting Category") + theme(legend.position = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_text(size=0)) +
  theme(axis.title.x = element_blank())+
  ggtitle("Wasting Category") + scale_y_sqrt() +
  ylab("sqrt(Rel. Abun.)")

pis_vibrio_plot


#plot with tissue type this time

pisaster_vibrio$DermisType2 <- factor(pisaster_vibrio$DermisType2, levels = c("H_healthy", "H_diseased", "L_diseased"))

pis_vibrio_plot2<-ggplot(pisaster_vibrio, aes(x = DermisType2, 
               y = Abundance, 
               color = DermisType2)) +
  #geom_boxplot() + 
  geom_jitter(width = 0.2, alpha = 0.7) +
  theme_classic() +
  ylab("Vpec Relative Abundance") +
  #facet_wrap(~SiteType) +
  scale_color_manual(values = c("olivedrab", "deepskyblue", "deepskyblue4"),
    name = "Wasting Category") + theme(legend.position = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_text(size=0)) +
  theme(axis.title.x = element_blank())+
  ggtitle("Wasting Category") + scale_y_sqrt() +
  ylab("sqrt(Rel. Abun.)")

pis_vibrio_plot2

#now plotting through time within wasting categories/tissue type

pisaster_vibrio$Season <- factor(
  pisaster_vibrio$Season,
  levels = c("Winter", "Spring", "Summer", "Fall"))

pisaster_vibrio$Month <- factor(
  pisaster_vibrio$Month,
  levels = c("1", "2", "5", "6", "7", "8", "9", "11", "12"))

pisaster_vibrio$DermisType2 <- recode(pisaster_vibrio$DermisType2,
  "H_healthy" = "Asym: Healthy",
  "H_diseased"     = "Wasting: NonLesion",
  "L_diseased"     = "Wasting: Lesion"
)

#facet by tissue type, across months
pis_vibrio_plot3<- ggplot(pisaster_vibrio, aes(x = Month, y = Abundance, color = Season)) +
  #geom_boxplot() +
  geom_jitter(aes(shape = SiteType), width = 0.3, alpha = 0.7) +
  theme_classic() +
  scale_color_manual(values = c("#05668D", "#00A896", "#9DD9D2", "#FE5E41")) + scale_y_sqrt() +
  ylab("sqrt(Rel. Abun.)") + #xlab("Tissue Type") +
  scale_shape_manual(values = c(8, 15), name = "Region") +
  facet_wrap(~DermisType2, axes = "all_x") + 
  theme(strip.background = element_blank()) + 
  ggtitle("P. ochraceus") + theme(plot.title = element_text(size = 10, face = "italic"))

pis_vibrio_plot3

#facet by wasting category, across months
pis_vibrio_plot4<- ggplot(pisaster_vibrio, aes(x = Month, y = Abundance, color = Season)) +
  #geom_boxplot() +
  geom_jitter(aes(shape = SiteType), width = 0.3, alpha = 0.7) +
  theme_classic() +
  scale_color_manual(values = c("#05668D", "#00A896", "#9DD9D2", "#FE5E41")) + scale_y_sqrt() +
  ylab("sqrt(Rel. Abun.)") + #xlab("Tissue Type") +
  scale_shape_manual(values = c(8, 15), name = "Region") +
  facet_wrap(~WastingCategory, axes = "all_x") + 
  theme(strip.background = element_blank()) + 
  ggtitle("P. ochraceus") + theme(plot.title = element_text(size = 10, face = "italic"))
  
  
pis_vibrio_plot4


```

combining the two panels

```{r}

vibrio_panel<-ggarrange(stars_vibrio_plot2, pis_vibrio_plot4, pis_vibrio_plot3, ncol=1, align = "v", labels = c("A", "B", "C"), common.legend = TRUE, legend = "right")

vibrio_panel

ggsave("vibrio_panel.jpeg", dpi=300, width=9, height=8, units="in")


```


